name: Build

on:
  push:
    paths:
      - "src/**"
      - "**.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "src/**"
      - "**.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup GHC with Stack
        uses: haskell/actions/setup@v2
        with:
          ghc-version: "9.2.5"
          enable-stack: true

      - name: Cache ~/.stack
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: ${{ runner.os }}-stack-global-

      - name: Cache .stack-work
        uses: actions/cache@v3
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: ${{ runner.os }}-stack-work-

      - name: Install system dependencies
        run: sudo apt-get install libxrandr-dev libxss-dev

      - name: Install dependencies
        run: |
          stack update
          stack build --only-dependencies --verbosity error

      - name: Build
        run: stack build

      - name: Run tests
        run: stack test
