name: Haskell CI

on:
  push:
    paths:
      - "lib/**"
      - "**.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "lib/**"
      - "**.hs"
      - "stack.yaml"
      - "**.cabal"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.8.4"
          cabal-version: "3.2"

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-cabal
        with:
          path: ~/.cabal
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run hlint
        uses: "domdere/haskell-lint-action@master"
        if: ${{ github.ref == 'refs/heads/develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install system dependencies
        run: sudo apt-get install libxrandr-dev libxss-dev

      - name: Install dependencies
        run: |
          cabal update
          cabal build --only-dependencies -j4

      - name: Build
        run: cabal build --enable-tests -j4 all

      - name: Run tests
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: cabal test all
